USER_STATUS_ACTIVE = 1
USER_STATUS_BLOCKED = 0

USER_TYPE_ADMIN = 1
USER_TYPE_USER = 2

CAR_NUMBER_STATUS_ACTIVE = 1
CAR_NUMBER_STATUS_BLOCKED = 0

CAR_NUMBER_TYPE_PERMANENT = 1
CAR_NUMBER_TYPE_TEMPORARY = 2
CAR_NUMBER_TYPE_ONE_TIME = 3

CAR_NUMBER_DETECTION_TIMEOUT = 60
